/* === CREATES === */
DROP TABLE FABRICANTES CASCADE CONSTRAINTS;
DROP TABLE ARTICULOS CASCADE CONSTRAINTS;

CREATE TABLE FABRICANTES(
	COD_FAB NUMBER(3) CONSTRAINT PK_FAB PRIMARY KEY,
	NOMBRE VARCHAR(50) UNIQUE
);

CREATE TABLE ARTICULOS(
	COD_ART NUMBER(3),
	NOMBRE VARCHAR(50) CONSTRAINT NB_UPPER CHECK(NOMBRE = UPPER(NOMBRE)),
	PRECIO NUMBER(10) CHECK (PRECIO>0),
	COD_FAB NUMBER(3) CONSTRAINT FK_ART REFERENCES FABRICANTES(COD_FAB) ON DELETE CASCADE,
	CONSTRAINT PK_ART PRIMARY KEY (COD_ART, COD_FAB)
);

/* INSERT FABRICANTES */
INSERT INTO FABRICANTES VALUES(1, 'Acer');
INSERT INTO FABRICANTES VALUES(2, 'Asus');
INSERT INTO FABRICANTES VALUES(3, 'Corsair');
INSERT INTO FABRICANTES VALUES(4, 'Dell');
INSERT INTO FABRICANTES VALUES(5, 'HP');
INSERT INTO FABRICANTES VALUES(6, 'Lenovo');
INSERT INTO FABRICANTES VALUES(7, 'Toshiba');

/* INSERT ARTICULOS */
INSERT INTO ARTICULOS VALUES(1, 'RADIO', 40, 1);
INSERT INTO ARTICULOS VALUES(2, 'TELEVISION', 200, 2);
INSERT INTO ARTICULOS VALUES(3, 'PORTATIL', 600, 1);
INSERT INTO ARTICULOS VALUES(4, 'TECLADO', 30, 2);
INSERT INTO ARTICULOS VALUES(5, 'TELEVISION', 220, 1);
INSERT INTO ARTICULOS VALUES(6, 'MONITOR', 150, 2);
INSERT INTO ARTICULOS VALUES(7, 'RATON', 15, 3);
INSERT INTO ARTICULOS VALUES(8, 'PROCESADOR', 300, 3);
INSERT INTO ARTICULOS VALUES(9, 'RAM', 120, 3);
INSERT INTO ARTICULOS VALUES(10, 'PLACA', 135, 3);
INSERT INTO ARTICULOS VALUES(12, 'PSU', 80, 1);
INSERT INTO ARTICULOS VALUES(13, 'PENDRIVE', 10, 4);
INSERT INTO ARTICULOS VALUES(14, 'PENDRIVE', 15, 4);

COMMIT;
/* EL COMMIT SOLO ES PARA LOS INSERTS */

/* ANTES DE LOS ALTER, METER TODAS LAS TABLAS Y LUEGO METER ALTERS 1 A 1 */
/* ALTER */
/*2.1- Añadir los campos DIRECCION y LOCALIDAD a la tabla fabricantes.*/
ALTER TABLE FABRICANTES ADD (
	DIRECCION VARCHAR(100),
	LOCALIDAD VARCHAR(50)
);

/*2.2- Eliminar la restricción de nombre en mayúsculas.*/
ALTER TABLE ARTICULOS DROP CONSTRAINT NB_UPPER;

/*2.3- Insertar la siguiente fila: altavoces de 70€ del fabricante 2.*/
INSERT INTO ARTICULOS VALUES(11, 'ALTAVOCES', 70, 2);

/*2.4- Cambiar el nombre del artículo 8 a ‘ impresora láser’.*/
UPDATE ARTICULOS SET NOMBRE='impresora láser' WHERE COD_ART=8;

/*2.5- Aplicar un descuento de 10€ a todos los artículos cuyo precio sea mayor 
igual a 120€.*/
UPDATE ARTICULOS SET PRECIO = PRECIO - 10 WHERE PRECIO > 120;






/* === CONSULTAS === */
/*3.1- Obtener los nombres de los productos.*/
SELECT NOMBRE FROM ARTICULOS;

/*3.2- Obtener los nombres y los precios de los productos cuyo precio sea menor 
que 200 euros.*/
SELECT NOMBRE, PRECIO FROM ARTICULOS WHERE PRECIO < 200;

/*3.3- Obtener todos los datos de los artículos cuyo precio este entre 60 y 120€.*/
SELECT * FROM ARTICULOS WHERE PRECIO BETWEEN 60 AND 120;