DROP TABLE FABRICANTES CASCADE CONSTRAINT;
CREATE TABLE FABRICANTES 
(
	COD_FAB NUMBER(3) CONSTRAINT PK_FAB PRIMARY KEY,
	NOMBRE VARCHAR(15) UNIQUE
);

DROP TABLE ARTICULOS CASCADE CONSTRAINT;
CREATE TABLE ARTICULOS 
(
	COD_ART VARCHAR(20),
	NOMBRE VARCHAR(20),
	PRECIO NUMBER(4),
	COD_FAB NUMBER(10) CONSTRAINT FK_ART REFERENCES FABRICANTES(COD_FAB) ON DELETE CASCADE,
	CONSTRAINT PK_ART PRIMARY KEY (COD_ART,COD_FAB),
	CHECK (PRECIO>0),
	CONSTRAINT NB_ART CHECK(NOMBRE = UPPER(NOMBRE))
);

/* INSERT FABRICANTES */
INSERT INTO FABRICANTES VALUES(1, 'Acer');
INSERT INTO FABRICANTES VALUES(2, 'Asus');
INSERT INTO FABRICANTES VALUES(3, 'Corsair');
INSERT INTO FABRICANTES VALUES(4, 'Dell');
INSERT INTO FABRICANTES VALUES(5, 'HP');
INSERT INTO FABRICANTES VALUES(6, 'Lenovo');
INSERT INTO FABRICANTES VALUES(7, 'Toshiba');

/* INSERT ARTICULOS */
INSERT INTO ARTICULOS VALUES(1, 'RADIO', 40, 1);
INSERT INTO ARTICULOS VALUES(2, 'TELEVISION', 200, 2);
INSERT INTO ARTICULOS VALUES(3, 'PORTATIL', 600, 1);
INSERT INTO ARTICULOS VALUES(4, 'TECLADO', 30, 2);
INSERT INTO ARTICULOS VALUES(5, 'TELEVISION', 220, 1);
INSERT INTO ARTICULOS VALUES(6, 'MONITOR', 150, 2);
INSERT INTO ARTICULOS VALUES(7, 'RATON', 15, 3);
INSERT INTO ARTICULOS VALUES(8, 'PROCESADOR', 300, 3);
INSERT INTO ARTICULOS VALUES(9, 'RAM', 120, 3);
INSERT INTO ARTICULOS VALUES(10, 'PLACA', 135, 3);
INSERT INTO ARTICULOS VALUES(12, 'PSU', 80, 1);
INSERT INTO ARTICULOS VALUES(13, 'PENDRIVE', 10, 4);
INSERT INTO ARTICULOS VALUES(14, 'PENDRIVE', 15, 4);

COMMIT;
/* EL COMMIT SOLO ES PARA LOS INSERTS */

/* ANTES DE LOS ALTER, METER TODAS LAS TABLAS Y LUEGO METER ALTERS 1 A 1 */
/* ALTER */
ALTER TABLE FABRICANTES ADD
(
	DIRECCION VARCHAR(20),
	LOCALIDAD VARCHAR(20)
);

ALTER TABLE ARTICULOS DROP CONSTRAINT NB_ART;

INSERT INTO ARTICULOS VALUES(11, 'altavoces', 70, 2);

UPDATE ARTICULOS SET NOMBRE='impresora láser' WHERE COD_ART=8;

UPDATE ARTICULOS SET PRECIO=(PRECIO-10) WHERE PRECIO>=120;

COMMIT;