/*para que salga el texto por consola (si no, no sale nada)*/
/*para que pregunte solo 1 vez para la var introducida x teclado*/
/*anchura de linea, en 200 suele estar bien*/
/*en caso de crear un bloque/procedimiento/funci?n con errores de compilaci?n */
SET SERVEROUTPUT ON;
SET VERIFY OFF;
SET LINESIZE 200;
SHOW ERRORS;



--EJERCICIO 1--
--BLOQUE ANONIMO QUE MUESTRE EL NUMERO TOTAL DE EMPLEADOS Y LA MEDIA DEL SALARIO CON UN DECIMAL--





--EJERCICIO 2--
--PROCEDIMIENTO QUE RECIBA UN EMP_NO. SI SU FECHA DE ALTA ES INFERIOR AL 1992, INCREMENTAR UN 10% SU SALARIO, DE LO CONTRARIO DISMINUIRLO UN 5%.--
--CONTROLAR EXCEPTION NO_DATA_FOUND. MOSTRAR EL ANTIGUO Y NUEVO SALARIO
--CABE DESTACAR QUE NO HE ENCONTRADO OTRA FORMA DE COMPARAR LA FECHA PORQUE SOY UN POCO CORTO QUIZA. DE ENCONTRAR UNA MANERA MAS ELEGANTE ESTARIA BIEN SABERLO--








--EJERCICIO 3--
--CREAR UN PROCEDIMIENTO QUE RECIBA UN EMP_ NO. CONTROLAR EXCEPCION SI EL OFICIO ES PRESIDENTE O SI EL APELLIDO ES GIL.-- 
-- MOSTRAR EL APELLIDO, OFICIO, EMP_NO Y SALARIO DEL EMPLEADO QUE SE HA PASADO POR TECLADO--


EXECUTE EJER3(7900);
EXECUTE EJER3(7788);
EXECUTE EJER3(7839);









--EJERCICIO 4-- 
--FUNCION QUE RECIBA COMO PARAMETRO UN NUMERO Y DEVUELVA SU CORRESPONDIENTE DIA DE LA SEMANA, DANDO POR HECHO QUE DOMINGO=1, LUNES=2 ETC ETC--

SELECT EJER4(5) FROM DUAL;










--EJERCICIO 5-- 
--MOSTRAR TODOS LOS NOMBRES DE LOS EMPLEADOS, SU EMP_NO Y EL NOMBRE DEL DEPARTAMENTO AL QUE PERTENECEN Y EL NUMERO TOTAL DE EMPLEADOS--









--EJERCICIO 6-- 
--TRIGGERS: CREAR UNA TABLA LIBROS Y OTRA TABLA CONTROL. INSERTAR, MODIFICAR O BORRAR EN LIBROS SE PLASMARA EN LA CONTROL CON LOS SIGUIENTES DATOS:--
--USER, FECHA Y 'STRING'. ESTE 'STRING' CORRESPONDERA AL TIPO DE ACCION QUE SE HAYA HECHO EN LA TABLA.--
DROP TABLE LIBROS_EX;
CREATE TABLE LIBROS_EX (
	COD NUMBER(4),
	TITULO VARCHAR(30),
	AUTOR VARCHAR(30)
);
DROP TABLE CONTROL;
CREATE TABLE CONTROL (
	USUARIO VARCHAR2(10),
	FECHA DATE,
	OPERACION VARCHAR2(20)
);





INSERT INTO LIBROS_EX VALUES(100, 'Me llamo Román', 'Román');
INSERT INTO LIBROS_EX VALUES(120, 'Me llamo Cosa', 'Cosa');
INSERT INTO LIBROS_EX VALUES(140, 'Me llamo Prueba', 'Jeje');
UPDATE LIBROS_EX SET COD=999 WHERE COD=100;
DELETE LIBROS_EX WHERE COD=140;







--EJERCICIO 7--
--CREAR UNA TABLE NUMEROS CON UNA COLUMNA COLUM1 DE TIPO NUMERO.--
--LLENAR LA TABLA DE NUMEROS DEL 1 AL 10 SIN EL 3 NI EL 8--
DROP TABLE NUMEROS;
CREATE TABLE NUMEROS (
	COLUM1 NUMBER
);




--AÑADIR, Y REPITO: AÑADIR, NO CREAR DE NUEVO, UNA COLUMNA COLUMN2 DE TIPO NUMERO Y CREAR UN PROCEDIMIENTO QUE LLENE LA COLUM2 CON UN NUMERO QUE ES LA POTENCIA CUADARADA DE SU CORRESPONDIENTE FILA--
--DE 1 SERA 1--
--DE 2 SERA 4--
--DE 4 SERA 16--
--ETC--


EXECUTE LLENAR_COL2;
SELECT * FROM NUMEROS;
/*ERROR CON FOR LOOP*/
--ME DA ERROR DE QUE NO COINCIDE EL TIPO DE VARIABLE E INTUYO QUE SE DEBE AL TIPO DE VARIABLE QUE PUDIERA SER I; PERO NO TENGO IDEA SINCERAMENTE.--


--AHORA SOBRE ESTA TABLA NUEVAMENTE AÑADIR UNA NUEVA COLUMNA COLUM3 DE TIPO VARCHAR(10)--
--CREAR UN PROCEDIMIENTO QUE LLENE ESTA COLUMNA CON STRINGS DEPENDIENDO SI LA COLUM2 ES PAR O IMPAR--
--CON LOOP--
ALTER TABLE NUMEROS ADD COLUM3 VARCHAR(20);



EXECUTE LLENAR_COL3;
SELECT * FROM NUMEROS;


-- VARIANTE CON FOR LOOP-- 


EXECUTE LLENAR_COL3;
SELECT * FROM NUMEROS;







--EJERCICIO 8--
--CREAR UNA FUNCION QUE RECIBA UN NUMERO Y HAGA EL FACTORIAL DEL MISMO, ADEMAS QUE SE DEVUELVA EL PROCESO ARITMETICO QUE HACE. EJEMPLO:
--4!=4*3*2*1. RESULTADO: 24--


SELECT EJER8(5) FROM DUAL;







--EJERCICIO 9--
--MOSTRAR LO SIGUIENTE--
/*
DEPARTAMENTO: 10 CONTABILIDAD
---- 7782 CEREZO
---- 7934 MU?OZ
---- 7839 REY
DEPARTAMENTO: 20 INVESTIGACION
---- 7566 JIMENEZ
---- 7369 SANCHEZ
---- 7788 GIL
---- 7902 FERNANDEZ
---- 7876 ALONSO
DEPARTAMENTO: 30 VENTAS
---- 7521 SALA
---- 7844 TOVAR
---- 7499 ARROYO
---- 7900 JIMENO
---- 7654 MARTIN
---- 7698 NEGRO
DEPARTAMENTO: 40 PRODUCCION
----
*/
--UNION EN LA RELACION NATURAL, IMPORTATE--

/* CON UNION SACA LOS DEPARTS VACÍOS, SIN UNION NO*/








--EJERCICIO 11--
/*
Escribir un programa que muestre, en formato similar a las rupturas de control, los siguientes datos:
Para cada empleado: apellido y salario
Para cada departamento: n? de empleados y suma de los salarios del departamento.
Al final del listado: n? total de empleados y suma de todos los salarios.
*/
--ESTE EJERCICIO ERA OPCIONAL, SOLO SE PODIA HACER SI TENIAS TODOS LOS OTROS EJERCICIOS RESUELTOS--
