REM ============ EJER 1 ============
CREATE TABLE AUDITAR_EMPLE(
	COL1 VARCHAR2(200)
);

SET SERVEROUTPUT ON;
SET VRIFY OFF;
CREATE OR REPLACE TRIGGER AUDITAR_SUBIDA_SALARIO
	AFTER UPDATE OF SALARIO ON EMPLE FOR EACH ROW
BEGIN
	INSERT INTO AUDITAR_EMPLE VALUES('SUBIDA SALARIO EMPLEADO*'||:OLD.EMP_NO);
END;
/

/* CADA VEZ QUE UPDATEEMOS SALARIO EN EMPLE, ME VA A INSERTAR LA SUBIDA DE SALARIO EN LA TABLA AUDITAR_EMPLE*/


REM ============ EJER 2 ============
SET SERVEROUTPUT ON;
SET VRIFY OFF;
CREATE OR REPLACE TRIGGER AUDITAR_BORRADO_EMPLE
	AFTER DELETE ON EMPLE FOR EACH ROW
BEGIN
	INSERT INTO AUDITAR_EMPLE VALUES('EMPLEADO BORRADO*'||:OLD.EMP_NO||'*'||:OLD.APELLIDO||'*'||:OLD.DEPT_NO);
END;
/

DELETE FROM EMPLE WHERE APELLIDO='SANCHEZ';


REM ============ EJER 3 ============

SET SERVEROUTPUT ON;
SET VRIFY OFF;
CREATE OR REPLACE TRIGGER AUDITAR_BORRADO_EMPLE
	AFTER DELETE ON EMPLE FOR EACH ROW WHEN(OLD.OFICIO='PRESIDENTE')
BEGIN
	INSERT INTO AUDITAR_EMPLE VALUES('EMPLEADO BORRADO*'||:OLD.EMP_NO||'*'||:OLD.APELLIDO||'*'||:OLD.DEPT_NO);
END;
/

DELETE FROM EMPLE WHERE OFICIO='PRESIDENTE';



REM ============ EJER 4 ============

SET SERVEROUTPUT ON;
SET VERIFY OFF;
CREATE OR REPLACE TRIGGER AUDITAR_SUBIDA_SALARIO
	AFTER DELETE OR INSERT ON EMPLE FOR EACH ROW
BEGIN
	IF INSERTING THEN
		INSERT INTO AUDITAR_EMPLE VALUES(SYSDATE ||:NEW.EMP_NO||'*'||:NEW.APELLIDO||'*'||:NEW.DEPT_NO||' - INSERTADO');
	ELSIF DELETING THEN
		INSERT INTO AUDITAR_EMPLE VALUES(SYSDATE ||:OLD.EMP_NO||'*'||:OLD.APELLIDO||'*'||:OLD.DEPT_NO||' - BORRADO');
	END IF;
END;
/

DELETE FROM EMPLE WHERE EMP_NO=7521;
INSERT INTO EMPLE VALUES(2, 'DIAZ','ANALISTA',7698,SYSDATE,1800,0,10);

/* SYSTIMESTAMP PARA FECHA, HORA Y + COSAS */




REM ============ EJER 5 (no entra)============

CREATE TABLE CONTROL_CONEXIONES(
USUARIO VARCHAR2(20),
MOMENTO TIMESTAMP,
EVENTO VARCHAR2(20)

SET SERVEROUTPUT ON;
SET VERIFY OFF;
CREATE OR REPLACE TRIGGER CTL_CONX
	AFTER LOGON ON DATABASE
BEGIN
	INSERT INTO CONTROL_CONEXIONES(USUARIO, MOMENTO, EVENTO) VALUES(ORA_LOGIN_USER,SYSTIMESTAMP, ORA_SYSEVENT);
END;
/
