REM *** EJERCICIO 1 *** 
CREATE OR REPLACE PROCEDURE LONGITUD(NUM1 NUMBER DEFAULT 2, PI NUMBER DEFAULT 3.14, radio NUMBER)
IS 
	LONGITUD NUMBER(5);
BEGIN 
	LONGITUD := 2*PI*radio;
	DBMS_OUTPUT.PUT_LINE('Longitud= '||LONGITUD);
END;
/

EXECUTE LONGITUD(20, 3.14, 50);





REM *** EJERCICIO 2 *** 
CREATE OR REPLACE PROCEDURE SAL_EMPLE(NUM_EMP NUMBER)
AS 
	V_SAL EMPLE.SALARIO%TYPE;
	REM **tabla.variable y con %
	REM **asignarle el mismo tipo que una columna de una tabla
BEGIN 
	SELECT SALARIO INTO V_SAL FROM EMPLE WHERE EMP_NO=NUM_EMP;
	DBMS_OUTPUT.PUT_LINE('Salario= '||V_SAL);
END;
/

EXECUTE SAL_EMPLE(7839);




REM *** EJERCICIO 3 ***
CREATE OR REPLACE PROCEDURE NOM_ASIG(COD_ASIG ASIGNATURAS.COD%TYPE)
IS 
	V_NOMBRE ASIGNATURAS.NOMBRE%TYPE;
BEGIN
	SELECT NOMBRE INTO V_NOMBRE FROM ASIGNATURAS WHERE COD=COD_ASIG;
	DBMS_OUTPUT.PUT_LINE('NOMBRE: '||V_NOMBRE);
END;
/

EXECUTE NOM_ASIG(7);






REM *** EJERCICIO 4 ***
CREATE OR REPLACE PROCEDURE NOM_PROFE(V_DNI PROFESORES.DNI%TYPE)
IS 
	V_NOMBRE PROFESORES.APELLIDOS%TYPE;
BEGIN
	SELECT APELLIDOS INTO V_NOMBRE FROM PROFESORES WHERE DNI=V_DNI;
	DBMS_OUTPUT.PUT_LINE('NOMBRE: '||V_NOMBRE);
END;
/

EXECUTE NOM_PROFE(9800990);





REM *** EJERCICIO 5 ***
CREATE OR REPLACE PROCEDURE VISUALIZAR_VENTAS(V_NOMBRE DEPART.DNOMBRE%TYPE)
IS 
	V_DEPT_NO DEPART.DEPT_NO%TYPE;
	V_LOC DEPART.LOC%TYPE;
BEGIN
	SELECT DEPT_NO, LOC INTO V_DEPT_NO, V_LOC FROM DEPART WHERE DNOMBRE=V_NOMBRE;
	DBMS_OUTPUT.PUT_LINE('EL DEPARTAMENTO Nº '||V_DEPT_NO||' ESTÁ EN: '||V_LOC);
END;
/

EXECUTE VISUALIZAR_VENTAS('VENTAS');







REM *** EJERCICIO 6 ***
CREATE OR REPLACE PROCEDURE INSERTAR_EMPLE(V_COD_EMP EMPLE.EMP_NO%TYPE, V_APELLIDO EMPLE.APELLIDO%TYPE, V_OFICIO EMPLE.OFICIO%TYPE, V_DEPT_NO EMPLE.DEPT_NO%TYPE)
IS
	V_
	V_DEPT_NO DEPART.DEPT_NO%TYPE;
	V_LOC DEPART.LOC%TYPE;
BEGIN
	SELECT DEPT_NO, LOC INTO V_DEPT_NO, V_LOC FROM DEPART WHERE DNOMBRE=V_NOMBRE;
	DBMS_OUTPUT.PUT_LINE('EL DEPARTAMENTO Nº '||V_DEPT_NO||' ESTÁ EN: '||V_LOC);
END;
/

EXECUTE VISUALIZAR_VENTAS('VENTAS');