PROCEDIMIENTOS 
	FORMATO:
		CREATE [OR REPLACE]  PROCEDURE <nbprocedimiento>
			[(<lista de parámetros>)]             
		IS
			[<declaraciones>]
		BEGIN
			<instrucciones>;
		[EXCEPTION
			<excepciones>;]
		END [<nbprocedimiento>];


*** ejercicio 1 *** 
CREATE OR REPLACE PROCEDURE LONGITUD(NUM1 NUMBER DEFAULT 2, PI NUMBER DEFAULT 3.14, radio NUMBER)
IS 
LONGITUD NUMBER(5);
BEGIN 
LONGITUD := 2*PI*radio;
DBMS_OUTPUT.PUT_LINE('Longitud= '||LONGITUD);
END;
/

*** ejercicio 2 *** 

CREATE OR REPLACE PROCEDURE SAL_EMPLE(NUM_EMP NUMBER)
AS 
V_SAL EMPLE.SALARIO%TYPE;
BEGIN 
SELECT SALARIO INTO V_SAL FROM EMPLE WHERE EMP_NO=NUM_EMP;
DBMS_OUTPUT.PUT_LINE('Salario= '||V_SAL);
END;
/

*** ejercicio 3 *** 

CREATE OR REPLACE PROCEDURE NOM_ASIG(COD_ASIG ASIGNATURAS.COD%TYPE);
IS 
V_NOMBRE ASIGNATURAS.NOMBRE%TYPE;
BEGIN
SELECT NOMBRE INTO V_NOMBRE FROM ASIGNATURAS WHERE COD=COD_ASIG;
DBMS_OUTPUT.PUT_LINE('NOMBRE: '||V_NOMBRE);
END;
/ 

***CORRECCION CARMEN***
CREATE OR REPLACE PROCEDURE CAMBIAR_OFICIO(NUM_EMP NUMBER,NUEVO_OFICIO VARCHAR2)
AS 
V_ANT_OFICIO EMPLE.OFICIO%TYPE;
BEGIN
SELECT OFICIO INTO V_ANT_OFICIO FROM EMPLE WHERE EMP_NO=NUM_EMP;
UPDATE EMPLE SET OFICIO=NUEVO_OFICIO;
DBMS_OUTPUT.PUT_LINE(NUM_EMP||'*OFICIO ANTERIOR'||V_ANT_OFICIO||'OFICIO NUEVO'|| NUEVO_OFICIO);
END; 
/


 