CREATE TABLE ASIGNATURA (
    COD_ASIG VARCHAR (10) PRIMARY KEY,
    NB_ASIG VARCHAR (20)
);


CREATE TABLE DEPARTAMENTO(
    COD_DEP VARCHAR (20) PRIMARY KEY,
    NB_DEP VARCHAR (20)
);

CREATE TABLE PROFESOR (
     DNI_PROF VARCHAR (20) PRIMARY KEY,
     NB_PROF VARCHAR (20),
     DIR_PROF VARCHAR (20),
     TF_PROF NUMBER (20),
     SUELDO_PROF NUMBER (10),
     COD_DEP VARCHAR (20),
     CONSTRAINT FK_DEP FOREIGN KEY (COD_DEP) REFERENCES DEPARTAMENTO(COD_DEP)
);

CREATE TABLE ALUMNO (
    DNI_ALUM VARCHAR (20) PRIMARY KEY,
    NB_ALUM VARCHAR (20),
    DIR_ALUM VARCHAR (20),
    TF_ALUM NUMBER (20),
    FECHA_NAC DATE
);

CREATE TABLE IMPARTE (
    COD_ASIG VARCHAR (10),
    DNI_PROF VARCHAR (20),
    DNI_ALUM VARCHAR (20),
    CONSTRAINT PK_IMP PRIMARY KEY (COD_ASIG,DNI_PROF,DNI_ALUM),
    CONSTRAINT FK_ASIG FOREIGN KEY (COD_ASIG) REFERENCES ASIGNATURA(COD_ASIG),
    CONSTRAINT FK_PROF FOREIGN KEY (DNI_PROF) REFERENCES PROFESOR(DNI_PROF),
    CONSTRAINT FK_ALUM FOREIGN KEY (DNI_ALUM) REFERENCES ALUMNO(DNI_ALUM)
);

/*HAY QUE PONER UN DNI QUE EXISTA PREVIAMENTE E IDEM CON LOS DEMÁS*/




DESC ASIGNATURA;
DESC DEPARTAMENTO;
DESC PROFESOR;
DESC ALUMNO;
DESC IMPARTE;

SELECT * FROM ASIGNATURA;
SELECT * FROM DEPARTAMENTO;
SELECT * FROM PROFESOR;
SELECT * FROM ALUMNO;
SELECT * FROM IMPARTE;
