DROP TABLE PROVINCIAS CASCADE CONSTRAINTS;
CREATE TABLE PROVINCIAS (
	COD_PROV NUMBER(2) CONSTRAINT PK_PROVINCIAS PRIMARY KEY CHECK (COD_PROV BETWEEN 1 AND 50),
	NB_PROV VARCHAR(10) NOT NULL UNIQUE
);

DROP TABLE PERSONAS CASCADE CONSTRAINTS;
CREATE TABLE PERSONAS (
	DNI VARCHAR(10) CONSTRAINT PK_PERSONAS PRIMARY KEY,
	NB VARCHAR(15) NOT NULL CHECK(NB=UPPER(NB)),
	DIR VARCHAR(20) NOT NULL,
	COD_PROV NUMBER(2) NOT NULL CONSTRAINT FK_PERSONAS REFERENCES PROVINCIAS(COD_PROV) ON DELETE CASCADE
);
