/* 12- Crear un procedimiento que reciba un número de empleado y una cadena correspondiente a su nuevo oficio. 
El procedimiento deberá localizar el empleado, modificar el oficio y visualizar los cambios realizados. */

CREATE OR REPLACE
PROCEDURE OFICIO_MOD(NUMEMPLE NUMBER, OFICIO VARCHAR)
IS
	V_NUMEMPLE NUMBER;
	V_OFICIO VARCHAR(10);
BEGIN
	SELECT EMP_NO, OFICIO INTO V_NUMEMPLE, V_OFICIO
	FROM EMPLE WHERE EMP_NO=NUMEMPLE;
	DBMS_OUTPUT.PUT_LINE ('')



CREATE OR REPLACE PROCEDURE VER_DEPART(NUMDEPART NUMBER)
IS
	V_DNOMBRE VARCHAR(14);
	V_LOCALIDAD VARCHAR(14);
BEGIN
	SELECT DNOMBRE, LOC INTO V_DNOMBRE, V_LOCALIDAD
	FROM DEPART WHERE DEPT_NO=NUMDEPART;
	DBMS_OUTPUT.PUT_LINE ('NUMDEPART:'||NUMDEPART||'*NB DEP:'||V_DNOMBRE||'*LOCALIDAD'||V_LOCALIDAD);
EXCEPTION
	WHEN NO_DATA_FOUND THEN
	DBMS_OUTPUT.PUT_LINE ('NUMDEPART:'||NUMDEPART||'*NB DEP:'||V_DNOMBRE||'*LOCALIDAD'||V_LOCALIDAD);
END;
/

EXECUTE VER_DEPART(10);
NUMDEPART:20*NB DEP:INVESTIGACION*LOCALIDADMADRID;