SET VERIFY OFF;
SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION CADENAREVES(PALABRA VARCHAR2)
RETURN VARCHAR2
IS 
	CADENA VARCHAR2(50);
BEGIN
	FOR i IN REVERSE 1..LENGTH(PALABRA) LOOP
	CADENA:=CADENA || SUBSTR(PALABRA,i,1);
	END LOOP;
	RETURN(CADENA);
END;
/

REM **COMO EJECUTAR
SELECT CADENAREVES('ABCDE') FROM DUAL; 