REM ****EJER 17**** Escribe una función que reciba una fecha y devuelva el año, en número, correspondiente a esa fecha
SET VERIFY OFF;
SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION ANNIO_F(FECHA DATE)
RETURN NUMBER
IS 
	ANNIO NUMBER;
BEGIN
	ANNIO := TO_NUMBER(TO_CHAR(FECHA, 'YYYY'));
	RETURN(ANNIO);
END;
/

REM **COMO EJECUTAR
SELECT ANNIO_F('24-12-2012') FROM DUAL;