REM ****EJER 19****
CREATE OR REPLACE FUNCTION SUMAR_IVA(CANTIDAD NUMBER, IVA NUMBER DEFAULT 16)
RETURN NUMBER
IS VALOR_SUMADO NUMBER;
BEGIN 
	VALOR_SUMADO := CANTIDAD+CANTIDAD*(IVA/100);
	RETURN(VALOR_SUMADO);
END;
/

REM **EJECUCIÓN
SELECT SUMAR_IVA(500, 20) FROM DUAL;
