DECLARE
	V_APELLIDO VARCHAR2(10);
	V_OFICIO VARCHAR2(10);
BEGIN
	SELECT APELLIDO, OFICIO INTO V_APELLIDO, V_OFICIO FROM EMPLE
	WHERE EMP_NO=7900;
	DBMS_OUTPUT.PUT_LINE(V_APELLIDO || ' ES: ' || V_OFICIO);
END;
/