/*7- Modificar el salario de un empleado especificado en función del número de empleados que tiene a su cargo:
	- Si no tiene ningún empleado a su cargo la subida será de 50€.
	- Si tiene un empleado la subida será de 80€.
	- Si tiene dos la subida será de 100€.
	- Si tiene mas de tres la subida será de 110€.
Además si el empleado es PRESIDENTE se incrementara en 30€.
Resolverlo con IF….ELSE y con CASE.	
Introduzca un valor para vt_empno: 7839
140
es presidente y tiene tres empleados a  su cargo 30+110=140
7839 rey        nulos         4100 PRESIDENTE antes de ejecutar
7839 rey        nulos         4240 PRESIDENTE despues de ejecutar */


SET VERIFY OFF;
DECLARE
	V_EMPLE_NO NUMBER;
	V_C_EMPLE NUMBER;
	V_AUMENTO NUMBER DEFAULT 0;
	V_OFICIO VARCHAR2(10); 
BEGIN
	V_EMPLE_NO:=&VT_EMPNO; /* para que no lo pida 2 veces en la select */
	SELECT OFICIO INTO V_OFICIO FROM EMPLE WHERE EMP_NO=V_EMPLE_NO;
	IF V_OFICIO='PRESIDENTE' THEN
		V_AUMENTO:=30;
	END IF;
	SELECT COUNT(*) INTO V_C_EMPLE FROM EMPLE WHERE DIR=V_EMPLE_NO;
	IF V_C_EMPLE=0 THEN
		V_AUMENTO:=V_AUMENTO+50;
	ELSIF V_C_EMPLE=1 THEN
		V_AUMENTO:=V_AUMENTO+80;
	ELSIF V_C_EMPLE=2 THEN
		V_AUMENTO:=V_AUMENTO+100;
	ELSE
		V_AUMENTO:=AUMENTO+110;
	END IF;
	UPDATE EMPLE SET SALARIO =SALARIO + V_AUMENTO WHERE EMP_NO =V_EMPLE_NO;
	DMBS_OUTPUT.PUT_LINE(V_AUMENTO);
END;
/


/* VARIANTE CON SWITCH */
SET VERIFY OFF;
DECLARE
	V_EMPLE_NO NUMBER;
	V_C_EMPLE NUMBER;
	V_AUMENTO NUMBER(5) DEFAULT 0;
	V_OFICIO VARCHAR2(10); 
BEGIN
	V_EMPLE_NO:=&VT_EMPNO;
	SELECT OFICIO INTO V_OFICIO FROM EMPLE WHERE EMP_NO=V_EMPLE_NO;
	IF V_OFICIO='PRESIDENTE' THEN
		V_AUMENTO:=30;
	END IF;
	SELECT COUNT(*) INTO V_C_EMPLE FROM EMPLE WHERE DIR=V_EMPLE_NO;
		WHEN 0 THEN V_AUMENTO:=V_AUMENTO+50;
		WHEN 1 THEN V_AUMENTO:=V_AUMENTO+80;
		WHEN 2 THEN V_AUMENTO:=V_AUMENTO+100;
	ELSE
		V_AUMENTO:=V_AUMENTO+110;
	UPDATE EMPLE SET SALARIO =SALARIO + V_AUMENTO WHERE EMP_NO =V_EMPLE_NO;
	DMBS_OUTPUT.PUT_LINE(V_AUMENTO);
END;
/