/* 8- Construir un bloque PL/SQL para que escriba la cadena HOLA al revés. Utilizando FOR, WHILE y LOOP.
ALOH */

/*CON FOR*/
SET VERIFY OFF;
DECLARE
	R_CADENA VARCHAR2(10); 
BEGIN
	FOR I IN REVERSE 1..LENGTH('HOLA') LOOP
		R_CADENA:=R_CADENA||SUBSTR('HOLA',I,1);
	END LOOP;
	DBMS_OUTPUT.PUT_LINE(R_CADENA);
END;
/

/*VARIANTE CON WHILE*/
SET VERIFY OFF;
DECLARE
	R_CADENA VARCHAR2(10);
	I BINARY_INTEGER;
BEGIN
	I=LENGTH('HOLA');
WHILE I>=1 LOOP
	R_CADENA:=R_CADENA||SUBSTR('HOLA',I,1);
	I:=I-1;
END LOOP;
	DBMS_OUTPUT.PUT_LINE(R_CADENA);
END;
/

/*VARIANTE CON LOOP*/
SET VERIFY OFF;
DECLARE
	R_CADENA VARCHAR2(10);
	I BINARY_INTEGER;
BEGIN
	I=LENGTH('HOLA');
LOOP
	R_CADENA:=R_CADENA||SUBSTR('HOLA',I,1);
EXIT WHEN I=1;
	I:=I-1;
END LOOP;
	DBMS_OUTPUT.PUT_LINE(R_CADENA);
END;
/