**** REM EJER 15 ****
SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION SUMANUM(NUM1 NUMBER, NUM2 NUMBER)
RETURN NUMBER
IS 
	SUMA NUMBER;
BEGIN
	SUMA:=NUM1+NUM2;
	RETURN(SUMA);
END;
/

--- como ejecutar ---
BEGIN DBMS_OUTPUT.PUT_LINE(SUMANUM(4,5));
END;
/

SELECT SUMANUM(4,5) FROM DUAL;

**** REM EJER 16 ****
SET VERIFY OFF;
SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION CADENAREVES(PALABRA VARCHAR2)
RETURN VARCHAR2
IS 
	CADENA VARCHAR2(50);
BEGIN
	FOR i IN REVERSE 1..LENGTH(PALABRA) LOOP
	CADENA:=CADENA || SUBSTR(PALABRA,i,1);
	END LOOP;
	RETURN(CADENA);
END;
/
 
--- como ejecutar ---
SELECT CADENAREVES('HOLA') FROM DUAL; 

**** REM EJER 17 **** Escribe una función que reciba una fecha y devuelva el año, en número, correspondiente a esa fecha
SET VERIFY OFF;
SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION ANNIO_F(FECHA DATE)
RETURN NUMBER
IS 
	ANNIO NUMBER;
BEGIN
	ANNIO := TO_NUMBER(TO_CHAR(FECHA, 'YYYY'));
	RETURN(ANNIO);
END;
/

--- como ejecutar ---
SELECT ANNIO_F('24-12-2012') FROM DUAL;

**** REM EJER 18 ****  Escribir una función que devuelva el valor con IVA de una cantidad que se pasara como primer parámetro. 
La función podrá recoger un segundo parámetro, que será el tipo de IVA siendo el valor por defecto 16.

SET VERIFY OFF;
SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION V_iva(CANTIDAD NUMBER, IVA NUMBER DEFAULT 16)
RETURN NUMBER
IS 
	VALOR NUMBER;
BEGIN
	VALOR := CANTIDAD + CANTIDAD * (IVA/100);
	RETURN(VALOR);
END;
/

--- como ejecutar ---
SELECT V_iva(12) FROM DUAL; 

**** REM EJER 18 ****
SET VERIFY OFF;
SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION V_iva(CANTIDAD NUMBER, IVA NUMBER DEFAULT 16)
RETURN NUMBER
IS 
	VALOR NUMBER;
BEGIN
	VALOR := CANTIDAD + CANTIDAD * (IVA/100);
	RETURN(VALOR);
END;
/